sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
linkReplacements:
  - "LICENSE-exasol-jdbc.txt|https://docs.exasol.com/db/latest/connect_exasol/drivers/jdbc.htm"
excludes:
  # Project is based on Lua, no need to build it with Java 17
  - "E-PK-CORE-17: Missing required file: '.github/workflows/ci-build-next-java.yml'"
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: false
  workflows:
    - name: "ci-build.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          job: "build-and-test"
          stepId: checkout
          content:
            name: "Cache downloaded LuaRocks packages"
            id: cache-luarocks
            uses: actions/cache@v6
            with:
              path: ~/.cache/luarocks
              key: ${{ runner.os }}-luarocks-lua-5.4-${{ hashFiles('*.rockspec') }}
        - action: INSERT_AFTER
          job: "build-and-test"
          stepId: cache-luarocks
          content:
            name: "Install Lua and LuaRocks"
            id: install-lua
            run: |
              sudo apt-get install lua5.4 liblua5.4-dev luarocks
              sudo update-alternatives --install /usr/bin/lua lua-interpreter /usr/bin/lua5.4 54
              sudo update-alternatives --install /usr/bin/luac lua-compiler /usr/bin/luac5.4 54
              sudo update-alternatives --set lua-interpreter /usr/bin/lua5.4
              sudo update-alternatives --set lua-compiler /usr/bin/luac5.4
              luarocks config --scope user lua_version 5.4
              luarocks config --scope user lua_dir /usr
              luarocks config --local deploy_bin_dir >> "$GITHUB_PATH"
              luarocks --lua-version=5.4 --local install --only-deps *.rockspec
        # Create a dummy Exasol error_code_report.json file with required fields:
        - action: INSERT_AFTER
          job: "build-and-test"
          stepId: build-pk-verify
          content:
            name: "Create dummy error report"
            id: error-report
            run: |
              echo '{
                  "errorReportVersion" : "1.0",
                  "errorCodes": []
              }' > target/error_code_report.json
        # Check the shell scripts
        - action: INSERT_AFTER
          job: "build-and-test"
          stepId: error-report
          content:
            name: "Check shell scripts"
            id: shell-check
            run: tools/shellcheck.sh
        - action: INSERT_AFTER
          job: "build-and-test"
          stepId: upload-artifacts
          content:
            name: "Upload Lua distribution artifact"
            id: upload-lua-distribution-artifact
            uses: actions/upload-artifact@v7
            with:
              name: lua-distribution
              path: target/exasol-virtual-schema-dist-*.lua
              if-no-files-found: error
              retention-days: 5
        - action: INSERT_AFTER
          job: "build-and-test"
          stepId: upload-lua-distribution-artifact
          content:
            name: "Upload LuaRocks rockspec artifact"
            id: upload-luarocks-rockspec-artifact
            uses: actions/upload-artifact@v7
            with:
              name: luarocks-rockspec
              path: exasol-virtual-schema-lua-*.rockspec
              if-no-files-found: error
              retention-days: 5
        # We don't need to test "Java next" compatibility in a Lua project:
        - action: REPLACE
          job: "next-java-compatibility"
          stepId: checkout
          content:
            id: skipped-checkout
            run: echo "Skipped next-Java checkout - Lua project"
        - action: REPLACE
          job: "next-java-compatibility"
          stepId: setup-java
          content:
            id: skipped-setup-java
            if: ${{ false }}
            run: echo Skipped
        - action: REPLACE
          job: "next-java-compatibility"
          stepId: build-next-java
          content:
            id: skipped-build-next-java
            if: ${{ false }}
            run: echo Skipped
    # Luarocks is also required in the release build:
    - name: "release.yml"
      stepCustomizations:
        - action: INSERT_AFTER
          job: "release"
          stepId: checkout
          content:
            name: "Install Lua, LuaRocks and Lua Dependencies"
            id: install-lua
            run: |
              tools/install_luarocks.sh --lua-version=5.4
              luarocks --lua-version=5.4 --local install --only-deps *.rockspec
        # Create a dummy Exasol error_code_report.json file with required fields:
        - action: INSERT_AFTER
          job: "release"
          stepId: build
          content:
            name: "Create dummy error report"
            id: error-report
            run: |
              echo '{
                  "errorReportVersion" : "1.0",
                  "errorCodes": []
              }' > target/error_code_report.json
        - action: INSERT_AFTER
          job: "release"
          stepId: create-github-release
          content:
            name: "Upload Lua distribution release artifacts"
            id: upload-lua-distribution-release-artifacts
            if: ${{ ! inputs.skip-github-release }}
            run: |
              gh release upload "$TAG" target/exasol-virtual-schema-dist-*.lua
              gh release upload "$TAG" exasol-virtual-schema-lua-*.rockspec
            env:
              GH_TOKEN: ${{ github.token }}
              TAG: ${{ steps.verify-release.outputs.release-tag }}
