@startuml
!include ../clean.skin

title: RLS Deployment Overview

node ExasolDataNode {
    component exasql {
        component Engine
        component Compiler
        component "Lua Interpreter" as interpreter
        Engine -l-> Compiler : invoke
        Compiler -d-> interpreter : call for Lua\nVirtual Schema\nfragments
    }

    artifact "row-level-security-dist.lua" as dist
    component "RLS Virtual Schema Adapter" as rls_vs_adapter
    
    interpreter -> dist : load
    interpreter -d-> rls_vs_adapter : execute
    dist -> rls_vs_adapter : define
    
}

database "Source Schema" as source
database "RLS Protected Schema" as protected

Engine - source
Engine - protected

source -[hidden]d- protected

url of rls_vs_adapter is [[../component/comp_rls_virtual_schema.svg]]
@enduml