' [dsn -> req~getting-the-suppoted-capabilities~1]

@startuml
!include ../clean.skin

title: Deployment Overview

node ExasolDataNode {
    component exasql {
        component Engine
        component Compiler
        component "Lua Interpreter" as interpreter
        Engine -l-> Compiler : invoke
        Compiler -d-> interpreter : call for Lua\nVirtual Schema\nfragments
    }

    artifact "exasol-virtual-schema-level-security-dist.lua" as dist
    component "Virtual Schema Adapter" as vs_adapter
    
    interpreter -> dist : load
    interpreter -d-> vs_adapter : execute
    dist -> vs_adapter : define
    
}

database "Source Schema" as source
database "Virtual Schema" as vs

Engine - source
Engine - vs

source -[hidden]d- vs

url of vs_adapter is [[../component/comp_virtual_schema.svg]]
@enduml