@startuml
!pragma layout smetana
!include ../clean.skin

title: Exasol Virtual Schema Components

component exasol-virtual-schema-lua {
    component entry

    package exasolvs {
        component ExasolAdapter
        component MetadataReaderFactory
        component QueryRewriter
        component AbstractMetadataReader
        component LocalMetadataReader
        component RemoteMetadataReader
        interface MetadataReader

        component RequestDispatcher
        component QueryRenderer
        interface "Adapter" <<interface>>

        ExasolAdapter .d.> MetadataReader : use
        RequestDispatcher .l.> Adapter : use
        ExasolAdapter -l-> QueryRewriter
        QueryRewriter -d-> QueryRenderer
        ExasolAdapter -r- Adapter
        AbstractMetadataReader -u- MetadataReader
        RemoteMetadataReader -u-|> AbstractMetadataReader
        LocalMetadataReader -u-|> AbstractMetadataReader
        MetadataReaderFactory --> LocalMetadataReader : create
        MetadataReaderFactory --> RemoteMetadataReader : create
    }
    
    entry -d-> RequestDispatcher : create
    entry -d-> ExasolAdapter : create
    entry -d-> MetadataReaderFactory : create

}

url of entry is [[../sequence/seq_entry.svg]]
url of RequestDispatcher is [[../sequence/seq_handle_request.svg]]
@enduml