@startuml
!include ../clean.skin

title: Exasol Virtual Schema Components

component exasol-virtual-schema-lua {
    component entry

    package exasolvs {
        component ExasolAdapter
        component MetadataReader
        component QueryRewriter

        ExasolAdapter -l-> MetadataReader
        ExasolAdapter -d-> QueryRewriter

        component RequestDispatcher
        component QueryRenderer
        interface "Adapter" <<interface>>
        note as interface_note
            Lua interface
            implicitly defined
        end note
        
        Adapter .d. interface_note
        
        QueryRewriter -d-> QueryRenderer
        RequestDispatcher .l.> Adapter : use
    }
    
    entry -d-> RequestDispatcher : create
    entry -d-> ExasolAdapter : create
    entry -d-> MetadataReader : create
    
    ExasolAdapter -r- Adapter
}

url of entry is [[../sequence/seq_entry.svg]]
url of RequestDispatcher is [[../sequence/seq_handle_request.svg]]
@enduml