@startuml
!pragma layout smetana
!include ../clean.skin
set separator none

title: Creation Chain Remote vs

package exasol.evsl {
    class entry <<function>>
    class ExasolAdapter
    class QueryRewriterFactory
    class RemoteQueryRewriter
    class MetadataReaderFactory
    class RemoteMetadataReader

    entry -d-> MetadataReaderFactory : "**1:** create"
    entry -r-> QueryRewriterFactory : "**2:** create"
    entry -d-> ExasolAdapter : "**3:** create"
    MetadataReaderFactory -d-> RemoteMetadataReader : "create"
    QueryRewriterFactory -r-> RemoteQueryRewriter : "create"


    url of entry is [[../sequence/seq_entry.svg]]
}

package exasol.vscl <<external>> {
    class QueryRenderer
    class RequestDispatcher

    url of RequestDispatcher is [[../sequence/seq_handle_request.svg]]
}

entry -d-> RequestDispatcher : "**4:** create"
RemoteQueryRewriter -->  QueryRenderer : create

@enduml