' [dsn -> req~creating-a-local-virtual-schema~1 >> impl, utest, itest]

@startuml
!include ../clean.skin

title: Create Virtual Schema

participant RequestDispatcher
participant ExasolAdapter
participant MetadataReader

activate RequestDispatcher
RequestDispatcher -> ExasolAdapter : create virtual schema (request)
activate ExasolAdapter
ExasolAdapter -> MetadataReader : read (schema, table[])
activate MetadataReader
ref over MetadataReader
    [[seq_read_local_schema_metadata.svg read local schema metadata]]
    or
    [[seq_read_remote_schema_metadata.svg read remote schema metadata]]
end
MetadataReader -->> ExasolAdapter : schema metadata
deactivate MetadataReader
ExasolAdapter -->> RequestDispatcher : schema metadata, adapter notes
deactivate ExasolAdapter
@enduml