' [dsn->req~excluding-capabilities~1]

@startuml
!include ../clean.skin

title: Get Capabilities

Participant RequestDispatcher
Participant ExasolAdapter

activate RequestDispatcher
RequestDispatcher -> ExasolAdapter : get capabilities (request)
activate ExasolAdapter
ExasolAdapter -> ExasolAdapter : subtract excluded capabilities()
activate ExasolAdapter
deactivate ExasolAdapter
ExasolAdapter -->> RequestDispatcher : capability[]
deactivate ExasolAdapter
@enduml