' [dsn -> req~reading-source-metadata~1]
' [dsn -> req~filtering-tables~1]

@startuml
!include ../clean.skin

title: Read Table Metadata

Participant MetadataReader

activate MetadataReader

alt table filter exists
    loop for each table in filter
        MetadataReader -> MetadataReader : translate table metadata (schema, table)
        activate MetadataReader
        deactivate MetadataReader
    end
else no table filter
    loop for each table in source schema
        MetadataReader -> MetadataReader : translate table metadata (schema, table)
        activate MetadataReader
        deactivate MetadataReader
    end
end
deactivate MetadataReader
@enduml