` [dsn -> req~dropping-a-virtual-schema~1]

@startuml
!include ../clean.skin

title: Drop Virtual Schema

Participant RequestDispatcher
Participant ExasolAdapter

activate RequestDispatcher
RequestDispatcher -> ExasolAdapter : drop virtual schema (request)
activate ExasolAdapter
ExasolAdapter -->> RequestDispatcher
deactivate ExasolAdapter 
@enduml