' [dsn -> req~setting-properties~1]

@startuml
!include ../clean.skin

title: Set Properties

Participant RequestDispatcher
Participant ExasolAdapter

activate RequestDispatcher
RequestDispatcher -> ExasolAdapter : set properties (request)
activate ExasolAdapter
ExasolAdapter -->> RequestDispatcher
deactivate ExasolAdapter
@enduml