' [dsn -> req~push-down~1]

@startuml
!include ../clean.skin

title: Query Push-down

Participant RequestDispatcher
Participant ExasolAdapter
Participant QueryRewriter
Participant QueryRenderer

activate RequestDispatcher
RequestDispatcher -> ExasolAdapter : push down (request)
activate ExasolAdapter
ExasolAdapter -> ExasolAdapter : extract adapter notes (request)
activate ExasolAdapter
deactivate ExasolAdapter
ExasolAdapter -> QueryRewriter : rewrite (query, schema\nadapter notes, involved table[])
activate QueryRewriter
ref over QueryRewriter : **[[../activity/act_rewrite_with_protection.svg rewrite query]]**

create QueryRenderer
QueryRewriter -> QueryRenderer : new(query)
activate QueryRenderer
QueryRenderer -->> QueryRewriter : instance
deactivate QueryRenderer
QueryRewriter -> QueryRenderer : render ()
activate QueryRenderer
QueryRenderer -->> QueryRewriter : query : SQL string
deactivate QueryRenderer
QueryRewriter --> ExasolAdapter : query : SQL string
deactivate QueryRewriter
ExasolAdapter -->> RequestDispatcher : wrapped response
deactivate ExasolAdapter
@enduml