' [dsn->req~refreshing-a-virtual-schema~1]
' [dsn->req~filtering-tables~1]

@startuml
!include ../clean.skin

title: Refresh Virtual Schema

Participant RequestDispatcher
Participant ExasolAdapter

activate RequestDispatcher
RequestDispatcher -> ExasolAdapter : refresh (request, table[])
activate ExasolAdapter
ExasolAdapter -> metadata_reader : read (schema)
activate metadata_reader
ref over metadata_reader : **[[seq_read_table_metadata.svg read table metadata]]**
metadata_reader -->> ExasolAdapter : schema metadata
deactivate metadata_reader
ExasolAdapter -->> RequestDispatcher : schema metadata, adapter notes
deactivate ExasolAdapter
@enduml