@startuml
!include ../clean.skin

title Dispatch Request

participant entry
participant RequestDispatcher
participant ExasolAdapter

activate entry
entry --> RequestDispatcher : adapter_call(request : JSON string)
activate RequestDispatcher
alt
    RequestDispatcher -> ExasolAdapter : [[seq_create_virtual_schema.svg create virtual schema (request)]]
    activate ExasolAdapter
else
    RequestDispatcher -> ExasolAdapter : [[seq_get_capabilities.svg get capabilities (request)]]
else
    RequestDispatcher -> ExasolAdapter : [[seq_set_properties.svg set properties (request)]]
else
    RequestDispatcher -> ExasolAdapter : [[seq_pushdown.svg pushdown (request)]]
else
    RequestDispatcher -> ExasolAdapter : [[seq_refresh.svg refresh (request)]]
else
    RequestDispatcher -> ExasolAdapter : [[seq_drop_virtual_schema.svg drop virtual schema(request)]]
end
activate ExasolAdapter
...
ExasolAdapter -->> RequestDispatcher : response
deactivate ExasolAdapter
RequestDispatcher -->> entry : response : JSON string
deactivate RequestDispatcher

@enduml