name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: "Assets upload URL"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: 5.4
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          luaRocksVersion: "3.9.1"
      - name: Install Lua dependencies
        run: luarocks --local install --only-deps *.rockspec
      - name: Build with Maven skipping tests
        run: mvn --batch-mode clean verify -DskipTests
      - name: Generate sha256sum files
        run: find target -maxdepth 1 -name *-dist-*.lua -exec bash -c 'sha256sum {} > {}.sha256' \;
      - name: Upload assets to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*-dist-*.lua
      - name: Upload sha256sum files
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.sha256
      - name: Upload error-code-report
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/error_code_report.json
